### ISSUE TITLE
Pebble and Bootstrap (3) out of the box?

### ISSUE THREAD

**Issue by decebals** [jochen777/jWebForm#4]
Can I use it with Pebble template engine and Bootstrap (3) without modifications?
I my mind (maybe I'm wrong) this means:
- you have already pebble's templates/macros
- you have already a Bootstrap (3) theme

**Comment by jochen777** [comment]
Yes, you can use it without modifications. The build in theme (jwebform-themes) can render a form without any template engine at all. (But to be honest: In a bigger/professional project, you want to style sooner or later your forms yourself. Then you can use the pebble-templates from the jWebformExample project as a starting point.)
The core should never needed to be touched - but you can greatly modfiy it by injecting different behaviours our your own input-fields.
Feel free to ask, if you need help to start!!
best regards - Jochen

**Comment by decebals** [comment]
Thanks for advices.
